### ISSUE TITLE
router_search fails if network inferface contains "default"

### ISSUE THREAD

**Issue by kb100** [jakewmeyer/Geo#10]
The regular expression in router_search should be more stringent. If any of the user's network interfaces contain "default" the router_search function may return incorrect results.

**Comment by jakewmeyer** [comment]
Do you have a more specific solution? In the vast majority of cases this should work, but I don't have a better solution currently.

**Comment by kb100** [comment]
I think grepping for "^default via" would solve the problem

**Comment by jakewmeyer** [comment]
Fixed in v0.1.9

Thanks 👍
