### ISSUE TITLE
Use https for network queries

### ISSUE THREAD

**Issue by kb100** [jakewmeyer/Geo#11]
None of the URLs that are curl'd use https. This is generally bad practice, though in your case because your scripts don't do more than print the output, an attacker could at best print unexpected things to the screen, perhaps tricking the user.

**Comment by jakewmeyer** [comment]
Looking into a better geolocation api that supports https

**Comment by jakewmeyer** [comment]
Using the current one because it supports newline separated output.

The other ones that I found are all json responses, which could be a problem in pure shell script without external dependencies. I would need to use an external json parser like jq to do it easily.

**Comment by kb100** [comment]
I would recommend using a json api and printing it with python (this can be done in a one-liner with `python -c`) This is a much more reasonable assumption that someone has python installed than jq.
