### ISSUE TITLE
Add IPv6 support for all IP queries

### ISSUE THREAD

**Issue by jakewmeyer** [jakewmeyer/Geo#18]

**Comment by jakewmeyer** [comment]
This will likely have to be a python script, since bash getopts doesn't support long flag options on Mac.

Example: For LAN search, ```-l4``` would be IPv4, while ```-l6``` would be IPv6

```-l``` would default to IPv4

**Comment by alexanderepstein** [comment]
There are other ways to include long options. One way would be to ```optionArgument=$( echo $@ | grep -Eo "\--optionName=[a-zA-Z]*" | sed s/"--optionName=/""/g)```
and then option argument would be equal to anything that came after ```---option=```.
