### ISSUE TITLE
Support long flags

### ISSUE THREAD

**Issue by kutsan** [jakewmeyer/Geo#20]
All of geo's flags are in short form. It would be better to provide alternate like `--wan` for `-w`, `--lan` for `-l` and such.

I know you are using `getopts` and it doesn't support long flags but still it is possible to implement.

**Comment by jakewmeyer** [comment]
Still looking for a good way to implement this without an external dependency, mainly for IPv6 support.

**Comment by kutsan** [comment]
@jakewmeyer This looks okay to me: https://stackoverflow.com/a/12523979/5649312

**Comment by kutsan** [comment]
@jakewmeyer Why?
