### ISSUE TITLE
Use 'ip' for MAC search

### ISSUE THREAD

**Issue by jhmartin** [jakewmeyer/Geo#8]
The ifconfig command is deprecated on several distributions (such as https://www.archlinux.org/news/deprecation-of-net-tools/), so consider testing for the existence of the newer `ip` command and use it instead:

```
$ ip link show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether b8:27:eb:02:29:6f brd ff:ff:ff:ff:ff:ff
```

**Comment by jakewmeyer** [comment]
Should be fixed in v0.1.6
